import Link from 'next/link';

export default async function Terms({ params }) {
  const resolvedParams = await params;
  const lang = resolvedParams.lang || 'en';

  return (
    <div className="min-h-screen bg-slate-50 py-16 px-6">
      <div className="max-w-3xl mx-auto bg-white p-10 rounded-2xl shadow-sm border border-slate-200">
        <Link href={`/${lang}`} className="text-blue-600 font-bold mb-8 inline-block hover:underline">&larr; Back to Tools</Link>
        <h1 className="text-3xl font-black text-slate-800 mb-6">Terms of Service</h1>
        <div className="prose prose-slate max-w-none text-slate-600 leading-relaxed space-y-4">
          <p><strong>Last Updated: May 2026</strong></p>
          <p>By accessing and using StackUtil, you accept and agree to be bound by the terms and provision of this agreement.</p>
          
          <h3 className="text-xl font-bold text-slate-800 mt-6 mb-2">1. Use of Tools</h3>
          <p>All tools and calculators provided on StackUtil are for informational and general utility purposes only. While we strive for accuracy, we make no guarantees regarding the exactness, reliability, or completeness of the results provided by any tool, including but not limited to currency exchange rates and size conversions.</p>
          
          <h3 className="text-xl font-bold text-slate-800 mt-6 mb-2">2. Liability</h3>
          <p>Under no circumstances shall StackUtil be liable for any direct, indirect, incidental, consequential, or punitive damages arising out of your use of, or inability to use, the website or the tools provided herein. You agree to use the data generated by this site at your own risk.</p>

          <h3 className="text-xl font-bold text-slate-800 mt-6 mb-2">3. Modifications</h3>
          <p>StackUtil reserves the right to modify or discontinue, temporarily or permanently, any tool or the site itself with or without notice. We reserve the right to update these terms at any time.</p>
        </div>
      </div>
    </div>
  );
}